// * Set Actions
export const GET_3ID_PROVIDER_REQUEST = 'GET_3ID_PROVIDER_REQUEST';
export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const SIGN_CLAIM_REQUEST = 'SIGN_CLAIM_REQUEST';
export const SIGN_CLAIM_SUCCESS = 'SIGN_CLAIM_SUCCESS';
export const SIGN_CLAIM_FAILURE = 'SIGN_CLAIM_FAILURE';
export const SET_WALLET_SUCCESS = 'SET_WALLET_SUCCESS';
